---
# tasks file for puppet
- name: Baixar o pacote do repo do puppet
  get_url:
   url: "https://apt.puppetlabs.com/puppetlabs-release-pc1-{{ ansible_distribution_release }}.deb"
   dest: /tmp/puppet.deb

- name: Instalar o repo do puppet
  apt:
   deb: /tmp/puppet.deb
   state: present

- name: Instalacao dos pacotess e deps do puppet
  apt: name={{ item }} update_cache=yes state=present
  with_items:
   - openssl
   - ntp
   - puppet-lint
   - puppet
   - puppet-common