---
# tasks file for create

- name: Verificando ambiente
  command: cat /tmp/log
  register: name

- name: Verificar a existencia de um container
  command: docker inspect {{ name.stdout }}
  register: container
  ignore_errors: yes

- name: Remover o container caso exista
  command: docker rm -f {{ name.stdout }}
  when: container.rc == 0
  ignore_errors: yes
 
- name: Realizar a criacao de um container do docker caso seja green
  command: docker run -dit --name {{ name.stdout }} --net=dexterlan --ip 10.0.0.42 --add-host devops.dexter.com.br:192.168.200.100 deploy /bin/bash
  when: container.rc == 0 and name.stdout == "green"

- name: realizar a criacao de um container do docker caso seja blue
  command: docker run -dit --name {{ name.stdout }} --net=dexterlan --ip 10.0.0.41 --add-host devops.dexter.com.br:192.168.200.100 deploy /bin/bash
  when: container.rc == 0 and name.stdout == "blue"

- name: habilitar o puppet agent no container
  command: docker exec {{ name.stdout }} puppet agent --enable

- name: rodar o puppet agente no container
  command: docker exec {{ name.stdout }} puppet agent -t --server devops.dexter.com.br
  ignore_errors: yes 

- name: remover pagina padrao do apache
  command: docker exec {{ name.stdout }} rm -f /etc/apache2/sites-enabled/000-default.conf
  
- name: Baixar a nova versao do codigo
  command: docker container exec {{ name.stdout }} git clone http://devops.dexter.com.br/devops/web.git /var/www/web

- name: restart apache
  command: docker exec {{ name.stdout }} service apache2 restart

- name: restart nginx
  command: service nginx restart

- name: docker compose 
  command: docker-compose -f /root/docker/compose/lab/docker-compose.yml up -d