---
# tasks file for docker
- name: Instalacao das deps do Docker-engine
  apt: name={{ item }} update_cache=yes state=present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
- name: Repo Docker Engine
  apt_repository:
   repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
   state: present

- name: Inclusao da chave do repo docker-eng
  apt_key: url="https://download.docker.com/linux/ubuntu/gpg" state=present

- name: Instalando o docker-eng
  apt: name=docker-ce update_cache=yes state=present
